In [1]:
## to install numpy library we need to use pip install

%pip install numpy



In [23]:
import numpy as np

arr1 = np.array([[2 , 3 , 4 , 5 , 6],[1 ,3 , 8 , 9 , 10]])

#no of element in the array
print(arr1.size)

## returns in form of (rows , columns)
print(arr1.shape)


## returns a new modified array , the changes are not inplace
print(arr1.reshape(5,2))

print(arr1)

10
(2, 5)
[[ 2  3]
 [ 4  5]
 [ 6  1]
 [ 3  8]
 [ 9 10]]
[[ 2  3  4  5  6]
 [ 1  3  8  9 10]]


In [27]:
np.arange(0 , 10 , 3).reshape(4,1)


array([[0],
       [3],
       [6],
       [9]])

In [33]:
print(np.ones((3 , 4 + 1))) ## forms a new array with all ones element

print(np.eye(8))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [37]:
arr1 = np.array([[1 , 2 , 3 , 4 , 5] , [6 , 7 , 8 , 9 , 10] , [11 , 12 , 13 , 14 , 15]])
arr2 = np.array([[1 , 2 , 3 , 4 , 5] , [6 , 7 , 8 , 9 , 10] , [11 , 12 , 13 , 14 , 15]])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr2 / arr1)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
arr1 = np.array([[1 , 2 , 3 , 4 , 5] , [6 , 7 , 8 , 9 , 10] , [11 , 12 , 13 , 14 , 15]])

## slicing and indexing
print(arr1[0])
print(arr1[2])

#to print first columns
print(arr1[0:3,0])

#to print last columns
print(arr1[0:3,4])

print(arr1[0:3,1:4])

print(arr1[0:2,0:2])

print(arr1[1][2:5])

print(arr1[1:])

print(arr1[0:2,2:5])

print(arr1[0:,1:4:2])

print(arr1[0:,2])

print(arr1[0:,3:5])

print(arr1[::-1])





[1 2 3 4 5]
[11 12 13 14 15]
[ 1  6 11]
[ 5 10 15]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
[[1 2]
 [6 7]]
[ 8  9 10]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 3  4  5]
 [ 8  9 10]]
[[ 2  4]
 [ 7  9]
 [12 14]]
[ 3  8 13]
[[ 4  5]
 [ 9 10]
 [14 15]]
[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [62]:
data = np.array([(x,y)for x in range(1 ,4)for y in range(1,3)])
data[0:] = 100
print(data)

data > 4
data[(data > 4) & (data <= 8)]


[[100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]]


array([], dtype=int64)